### ISSUE TITLE
Proper window resize

### ISSUE THREAD

**Issue by ohenley** [ohenley/covidsim#5]
At one point I contemplated a move to QML to inherit some 'flexbox' like capabilities. It's either that or someone finds how to support/implement proper window resize with *.ui config. 

(The main gotcha is specific simulation engine properties make use of different area estate and I never found how to make the whole thing adapt dynamically when switching between eg. xph and lancet simulation engine)

**Comment by mgrojo** [comment]
I can take a look at this. I haven't worked with QML, but this should be feasible using the UI approach.
